# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmessage.proto\"f\n\x0b\x43oordinates\x12%\n\x04unit\x18\x01 \x03(\x0b\x32\x17.Coordinates.Coordinate\x12\x12\n\nLaser_type\x18\x02 \x01(\t\x1a\x1c\n\nCoordinate\x12\x0e\n\x06values\x18\x01 \x03(\x01\x62\x06proto3'
)




_COORDINATES_COORDINATE = _descriptor.Descriptor(
  name='Coordinate',
  full_name='Coordinates.Coordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='Coordinates.Coordinate.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=119,
)

_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit', full_name='Coordinates.unit', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Laser_type', full_name='Coordinates.Laser_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COORDINATES_COORDINATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=119,
)

_COORDINATES_COORDINATE.containing_type = _COORDINATES
_COORDINATES.fields_by_name['unit'].message_type = _COORDINATES_COORDINATE
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), {

  'Coordinate' : _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
    'DESCRIPTOR' : _COORDINATES_COORDINATE,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:Coordinates.Coordinate)
    })
  ,
  'DESCRIPTOR' : _COORDINATES,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  })
_sym_db.RegisterMessage(Coordinates)
_sym_db.RegisterMessage(Coordinates.Coordinate)


# @@protoc_insertion_point(module_scope)
