# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: new_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='new_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11new_message.proto\"@\n\x10\x43oordinatesBytes\x12\x18\n\x10\x63oordinates_data\x18\x01 \x01(\x0c\x12\x12\n\nLaser_type\x18\x02 \x01(\tb\x06proto3'
)




_COORDINATESBYTES = _descriptor.Descriptor(
  name='CoordinatesBytes',
  full_name='CoordinatesBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates_data', full_name='CoordinatesBytes.coordinates_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Laser_type', full_name='CoordinatesBytes.Laser_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=85,
)

DESCRIPTOR.message_types_by_name['CoordinatesBytes'] = _COORDINATESBYTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoordinatesBytes = _reflection.GeneratedProtocolMessageType('CoordinatesBytes', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATESBYTES,
  '__module__' : 'new_message_pb2'
  # @@protoc_insertion_point(class_scope:CoordinatesBytes)
  })
_sym_db.RegisterMessage(CoordinatesBytes)


# @@protoc_insertion_point(module_scope)
